# Leave this file empty to ensure that CI runs builds against the default configuration in values.yaml.
# Except for the Access Token which is a required input
synthetics:
  privateLocationKey: "abcdefgh-jklm-opqr-tuwx-z1234567890z"
